baseURL = "https://bruno-anjos.github.io"
title = "Bruno Anjos"
themesDir = "themes"
theme = "m10c"
paginate = 5

[params]
	author = "Bruno Anjos"
	description = """Computer Science student, currently in my masters' degree last year.
	I'm mostly interested in Computer Systems Architecture, Distributed Systems,
	Computer Networks and Security associated with all these topics."""
	avatar = "avatar.png"

	[[params.social]]
		name = "github"
		url = "https://github.com/bruno-anjos"
	[[params.social]]
		name = "mail"
		url = "mailto:bruno.vale.anjos@gmail.com"
	[[params.social]]
		name = "linkedin"
		url = "https://www.linkedin.com/in/bruno-vale-anjos/"
		

#   Brown theme
#   [params.style]
#    darkestColor = "#463625"
#    darkColor = "#2a3738"
#    primaryColor = "#eeee6a"
#    lightColor = "#96a879"
#    lightestColor = "#ffffff"

# Green theme
#   [params.style]
#    darkestColor = "#315659"
#    darkColor = "#253031"
#    primaryColor = "#dad865"
#    lightColor = "#96a879"
#    lightestColor = "#fff"

#   Red and black theme
#   [params.style]
#    darkestColor = "#d35050"
#    darkColor = "#212121"
#    primaryColor = "#ffffff"
#    lightColor = "#a2a2a2"
#    lightestColor = "#d3d3d3"

[params.style]
	darkestColor = "#d35050"
	darkColor = "#212121"
	lightColor = "#f5e3e0"
	lightestColor = "#f5f5f5"
	primaryColor = "#fff"
