baseurl = "https://bruno-anjos.github.io/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = false
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
	title = "Bruno Anjos"
	subtitle = ""
	keywords = ""
	copyright = "© 2019 Bruno Anjos :: Powered by Hugo :: Theme made by panr"
	menuMore = "Show more"
	readMore = "Read more"
	readOtherPosts = "Read other posts"

	[languages.en.params.logo]
	  logoText = "Bruno Anjos"
	  logoHomeLink = "/"

	[languages.en.menu]
		[[languages.en.menu.main]]
			identifier = "posts"
			name = "Posts"
			url = "/posts"
		[[languages.en.menu.main]]
			identifier = "about"
			name = "About"
			url = "/about"
		[[languages.en.menu.main]]
			identifier = "showcase"
			name = "Theme Showcase"
			url = "/showcase"