baseurl = "https://bruno-anjos.github.io"
languageCode = "en-us"
theme = "light-hugo"

title = "Bruno Anjos"
author = "Bruno Anjos"
copyright = "© Copyright 2019 Bruno Anjos"

[Params]
  description = "Describe your website"
  email = "john@example.org"
  github = "tblyler"
  twitter = "tonyblyler"
  linkedin = "johndoe"
  facebook = "johndoe"
  youtube = "johndoe"
  logo = "/img/avatar.png"